### ISSUE TITLE
roundDomains=true in LineChart causes error

### ISSUE THREAD

**Issue by ctaepper** [swimlane/ngx-charts#254]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

chart is throwing an error, see plunkr

**Expected behavior**

chart should work fine and axis should be rounded

**Reproduction of the problem**

https://plnkr.co/edit/k7Y9YYq2afHtbGDDdWPN

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
osx/npm/latest chrome

* **ngx-charts version:** 4.2.0
* **Angular version:** 4.0.0-rc0 but also won't work in 2.x
* **Browser:** all
* **Language:** Typescript 2.1

**Comment by tstock55** [comment]
This issue is on the documentations plnkr as well. The error that is thrown is something like "scale.nice is not a function"

**Comment by jmls** [comment]
urgh - any feedback on this . I just hit a `inline template:36:18 caused by: scale.nice is not a function` error

**Comment by marjan-georgiev** [comment]
Should be fixed in 4.4.0 (angular 2.x) and 5.0.0 (angular 4.x)

**Comment by sjdemoor** [comment]
This error is still being thrown (as of version 9.0.0):  The problem comes from implementing roundDomains on both the Y-axis (which is always numeric) and the X-axis (which can sometimes be categorical/string).  

You need to disable the roundDomains functionality on the X-axis when the "name" fields in a series are not a numeric type.  Ie., roundDomains works when the "name" fields in all of the series are of types `Date()` and `number` -- but not `string`.
