### ISSUE TITLE
Update deps to Angular 6 and rxjs 6

### ISSUE THREAD

**Issue by AlQuraian** [swimlane/ngx-charts#823]
**What is the motivation / use case for changing the behavior?**
- To keep up with the latest and greatest
- Reduce code size and improve build speed

**Comment by byunru** [comment]
current version 7.3.0 run-time fail with Angular 6, EVEN with the  help of "rxjs-compat": "6",

------------------------------------------------------------------------------------------
index.js:57266 Uncaught TypeError: Object(...) is not a function
    at index.js:57266
    at Object../src/index.ts (index.js:57292)
    at __webpack_require__ (index.js:35)
    at ./node_modules/angular2-moment/add.pipe.js.__decorate (index.js:78)
    at index.js:81
    at webpackUniversalModuleDefinition (index.js:8)
    at Object../node_modules/@swimlane/ngx-ui/release/index.js (index.js:15)

**Comment by GO3LIN** [comment]
For me, with the version 7.3.0, I can serve my application locally, but when I try to build it for production, I got this errors:

ERROR in ./node_modules/@swimlane/ngx-charts/release/common/base-chart.component.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in '/xxx/node_modules/@swimlane/ngx-charts/release/common'
ERROR in ./node_modules/@swimlane/ngx-charts/release/common/base-chart.component.js
Module not found: Error: Can't resolve 'rxjs/operators/debounceTime' in '/xxx/node_modules/@swimlane/ngx-charts/release/common'

**Comment by EricSmekens** [comment]
Could you try 7.4.0?

**Comment by EricSmekens** [comment]
@byunru Yes, I can see this error also in my PR. #827 
Possible to share code? I think it is because ngx-ui doesn't support it yet?

**Comment by Koslun** [comment]
Given https://github.com/swimlane/ngx-charts/pull/812 I think this issue has been resolved and can be closed?

**Comment by EricSmekens** [comment]
Not, cannot be closed. #812 broke the tests, #827 fixes this, but the demo page is still not working, due to devDepedancies that are not compatible with NG6.

**Comment by AlQuraian** [comment]
Yep. I get the following build errors:

```
ERROR in ./node_modules/@swimlane/ngx-charts/release/common/base-chart.component.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in 'D:\code\**\node_modules\@swimlane\ngx-charts\release\common'
ERROR in ./node_modules/@swimlane/ngx-charts/release/common/base-chart.component.js
Module not found: Error: Can't resolve 'rxjs/operators/debounceTime' in 'D:\code\**\node_modules\@swimlane\ngx-charts\release\common'
```

**Comment by hesampour** [comment]
the same problem. I get the following error: 
Package "ngx-charts" has an incompatible peer dependency to "rxjs" (requires "5.0.1", would install "6.1.0").

**Comment by marjan-georgiev** [comment]
Released in ngx-charts 8.0.0

**Comment by GO3LIN** [comment]
Tested serving and build in prod mode, it works like charm now ! Big thanks @marjan-georgiev ;-)
