### ISSUE TITLE
Bootstrap.css affects the pie chart

### ISSUE THREAD

**Issue by rockers7414** [swimlane/ngx-charts#98]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The pie chart doesn't display normally. It displays at the strange position that is not as same as the demo. It'll display well if I remove the bootstrap.css out of my project.

**Expected behavior**
The chart could display well with the bootstrap.css.

* **ng2d3 version:** x.x.x
1.6.0

* **Angular version:** 2.x.x
2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3

**Comment by amcdnl** [comment]
Can you make a demo please?

**Comment by rockers7414** [comment]
Below link is the demo. As you can see, the legend is displayed at the bottom of the pie chart, and has one border under the legend. I think it's affected by the bootstrap css (legend).

https://plnkr.co/edit/DW8GOlvHWtps1vsbJj4c?p=preview

**Comment by marjan-georgiev** [comment]
Fixed in master, will come with the next release.

**Comment by pblasco** [comment]
I think this bug might still be an issue with bootstrap 4.  The legend still appears below the chart rather than beside it.

https://plnkr.co/edit/TEepr2KK5NgWQ3XPXVZf?p=preview

This was also happening using a bar chart in a project of mine.  I forked the previous plnkr and changed it to bootstrap 4 and it occurs there.

**Comment by frosenberg** [comment]
Does the plunker still work for you?

**Comment by pblasco** [comment]
Looks like the plunker is broken.

**Comment by marjan-georgiev** [comment]
I  upgraded master to angular 2.3.0 and rxjs 5. The plunkers always pull the latest version from master and their other dependencies are behind now. I'm trying to get them updated.

**Comment by marjan-georgiev** [comment]
Here's an updated plunker.

You are right, this is an issue again. There will be a fix in the next version. Meanwhile, if you are still using angular 2.2.x and ng2d3 2.0.0, you can fix this by overriding the width css:
```
.chart-legend {
    width: auto;
}
```

**Comment by marjan-georgiev** [comment]
Fixed in 3.0.3
